version: "3.8"

networks:
  rag-network:
    driver: bridge

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - rag-network
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,generative-openai"
      OPENAI_APIKEY: ${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 15s
      timeout: 10s

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.txt
    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - rag-network
    depends_on:
      weaviate:
        condition: service_healthy
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_DIR=/app/data
    volumes:
      - app_data:/app/data

volumes:
  weaviate_data:
  app_data:
